### ISSUE TITLE
Port Ville-de-Laval to OntoRefine

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-ville-de-laval#2]
Ville-de-laval should have a workflow that uses OntoRefine to get the JSON dump from a web portal called Données Quebec, convert to JSON-LD and push to the Artsdata Databus.

The artsdata-planet-ville-de-laval repo **already has an OntoRefine schema**, but the process is not automated.

Please refer to the automation in artsdata-planet-footlight as a base for running OntoRefine in a workflow. Try to keep it DRY and make improvements to both workflows.

**Comment by dev-aravind** [comment]
@saumier The data for ville-de-laval is up in nebula. Please review it and let me know if you need any changes. 
Data - [Events](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Event%20entities%20in%20donnees-quebec-ca%20%286147%20triples%29&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/donnees-quebec-ca), [Places](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Place%20entities%20in%20donnees-quebec-ca%20%286147%20triples%29&sparql=list_places&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/donnees-quebec-ca)

**Comment by saumier** [comment]
Looking really good. A few comments

1. Use the same artifact name calendrier-activites as before which is the file name of the data feed on Données Quebec. 

2. Challenge: Try to find the places in the data portal Données Quebec and load them with their own artifact name. Since the portal is only in French you may not be able to find a dataset for Laval places. Time box this to about an hour and then let me know and I can search the portal  to try and find the places. But if you do find the places then map them to RDF keeping the Artsdata required properties for Place including a nested PostalAddress.

**Comment by dev-aravind** [comment]
@saumier Is [this](https://www.donneesquebec.ca/recherche/dataset/lieux-et-edifices-municipaux) the correct URL for the places dataset?

**Comment by saumier** [comment]
@dev-aravind That data feed does not look useful for our needs. I don't see any way to link Ids to the places in the events data feed.

**Our goal is to be able to have data on the places for all events**

Currently I created the [place mapping file](https://github.com/culturecreates/artsdata-planet-ville-de-laval/blob/main/mapping/place-mapping-to-artsdata.ttl) but this needs to be maintained manually which is not great.

So we need a data feed to get full names and addresses of the locations for all events.

If there is no data feed that can be linked to the place ids, then I propose the following idea: If you look in the events data feed you see that events have data like this "Locations":[{"Id":"c62843eb-d9d1-440a-9c38-632da61f7ff3","Label":"Hôtel de ville","TargetUrl":"/lieux/Pages/Fr/hotel-de-ville.aspx","CustomProperties":null}]

If you use the TargetUrl of the location then perhaps you can scrape the JSON-LD from the webpage https://www.laval.ca/lieux/Pages/Fr/hotel-de-ville.aspx

You can give that a try, or look for other data feeds that reach our goal.

**Comment by dev-aravind** [comment]
@saumier The places data is up in nebula. Please review it and let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind This is looking very good. A few little additions before closing this issue.
- [ ]  Modify your replace-blank-nodes.sparql  to pass the tests I added `ruby replace_blank_nodes_test.rb`.  Your sparql was merging multiple classes into one. For example, the classes schema:LocalBusiness and schema:BreadcrumbList were getting merged into the same entity. There are multiple top level entities on the webpage, so you can't assign the name URI to all the entities because they will get merged.
```
<https://www.laval.ca/afa7201f-6aab-4196-b349-66674653729b> a <http://schema.org/Place>,
    <http://schema.org/LocalBusiness>,
    <http://schema.org/BreadcrumbList> 
```
- [x] Add  prov:wasDerivedFrom [url of webpage scraped] for the place entites similar to what you did in IPAA. To test this you should be able to click the Place's prov:wasDerivedFrom and then click "dereference" so view the actual webpage data in Nebula.
- [x] Set the workflow schedule to weekly on Wednesday mornings to allow the CMS to load new events every week
- [x] As a general note, please use snake_case to name files with ruby code, and use CamelCase for the class name. Example replace_blank_nodes_test.rb is the file and ReplaceBlankNodesTest is the class in the file.

I removed my old Place mapping files, my old workflows and old data dumps as they are no longer needed. The repo is now much cleaner and has only what is currently being used.

**Comment by dev-aravind** [comment]
@saumier The data scraped from the Laval website has location type as [schema.org/LocalBusiness](https://schema.org/LocalBusiness). But the data that our Ontorefine config generates has the type [https://schema.org/Place] (https://schema.org/Place) So should I remove the LocalBusiness type and keep it as Place or keep both of the types?|

You can find the updated data [here](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/query/show?title=Place%20entities%20in%20calendrier-activites%20%285717%20triples%29&sparql=list_places&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/calendrier-activites)

**Comment by saumier** [comment]
@dev-aravind In this case I think we should keep both schema:Place and the original schema:LocalBusiness. We should also add sub-types of schema:Places to the SPARQL including schema:LocalBusiness and other sub-types. I leave it to you to find the schema.org sub-types for schema:Places and add them to the SPARQL that replaces blank nodes and check that the tests pass.

When the schema.org ontology is loaded into the graph then inferencing will find all schema:LocalBusiness when looking for schema:Places. But since we generally don't turn on inferencing when we collect the JSON-LD on webpages we can keep both, and include sub-types in the SPARQL since we don't know in the future if some other types of Organizations will be used.

**Comment by dev-aravind** [comment]
@saumier I fixed the unit test issue by also including the schema:Place type in the add derived from SPARQL. Please review it and let me know if you find any issues.

**Comment by saumier** [comment]
@dev-aravind I refactored your sparql to make it more compact and easier to read, and then I added another test to check all the additional types of Places defined in schema.org.

Please complete the sparql to make the tests pass ;-)

**Comment by dev-aravind** [comment]
@saumier I updated the SPARQL to make the new test that you added to pass. Please review it and let me know if you need any more changes.
