### ISSUE TITLE
Split Event in multiple locations?

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-ville-de-laval#4]
As an admin of Signé Laval, I receive a data feed from [La Ville de Quebec](https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-ville-de-laval%2Fcalendrier-activites) which often has events with 2 locations. This causes a validation error and the events are not sent to Footlight CMS.  I would like the events to be split per location so that can be sent to the CMS.

NOTE: These events are coming up in November and Maude really wants these events in CMS in the coming days or else she will have to decide if she can enter them by hand, so we should get back to her if we can help her or not on Thursday.

Ideas:
This is for discussion as I am not sure if these are good ideas or really bad ideas ;-)
- Modify the data before converting and sending to Artsdata Databus (this is preferred because it impacts only this data source)
OR
- Modify Aggregator to make a copy of events per location (feels dangerous to me)

### Example minted as a test
http://kg.artsdata.ca/resource/K43-845

https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Ffestival-num-secrets-foret.aspx

### Examples not minted
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Ffestival-num-monsieur-crabe.aspx
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Ffestival-num-stop-motion-lego-compagnie.aspx
...
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Ffestival-num-maison-musicale.aspx
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Ffestival-num-buzz-wall.aspx

**Comment by suhail-aliyar** [comment]
@saumier I think we can handle this in the aggregator itself. It doesn't look dangerous to me as we are doing the same approach for event series. 
For this approach it should not take more than a day to complete it.

**Comment by saumier** [comment]
@sahalali Lets do it :-)

**Comment by saumier** [comment]
@sahalali Nope. I took another look, and the intent of the event [Les secrets de la forêt](https://www.laval.ca/Pages/Fr/Calendrier/festival-num-secrets-foret.aspx) is NOT to have the events in both locations.

@troughc I am going to return to Maude saying we don't have any ideas on how to fix this.

**Comment by saumier** [comment]
This was followed up with Caitlin who is communicating with Maude.
